/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hassan.askar.easymcu;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author askar
 */
public class EasyMCU extends javax.swing.JFrame {

    /**
     * Creates new form EasyMCU
     */
    AskarFile aFile = new AskarFile();
    DynamicView DV = new DynamicView();
    Color panelMovingColor = new Color(41, 57, 80);
    Color labelMovingColor = new Color(255, 128, 0);

    public EasyMCU() {
        initComponents();
        logoLabel.setIcon(new ImageIcon("Images/EasyMCU_Logo.png"));
        newProjectIconLabel.setIcon(new ImageIcon("Images/new.png"));
        calculatorIconLabel.setIcon(new ImageIcon("Images/calc.png"));
        learnIconLabel.setIcon(new ImageIcon("Images/learn.png"));
        openProjectIconLabel.setIcon(new ImageIcon("Images/open.png"));
        aboutIconLabel.setIcon(new ImageIcon("Images/about.png"));
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        newProjectPanel = new javax.swing.JPanel();
        pointerNewProjectPanel = new javax.swing.JPanel();
        newProjectLabel = new javax.swing.JLabel();
        newProjectIconLabel = new javax.swing.JLabel();
        CalculatorPanel = new javax.swing.JPanel();
        pointerCalculatorPanel = new javax.swing.JPanel();
        calculatorLabel = new javax.swing.JLabel();
        calculatorIconLabel = new javax.swing.JLabel();
        LearnPanel = new javax.swing.JPanel();
        pointerLearnPanel = new javax.swing.JPanel();
        learnLabel = new javax.swing.JLabel();
        learnIconLabel = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        pointerAboutPanel = new javax.swing.JPanel();
        aboutLabel = new javax.swing.JLabel();
        aboutIconLabel = new javax.swing.JLabel();
        generalPanel = new javax.swing.JPanel();
        recentProjectsPanel = new javax.swing.JPanel();
        exitLabel = new javax.swing.JLabel();
        easyMCULabel = new javax.swing.JLabel();
        recentProjectsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        openProjectPanel = new javax.swing.JPanel();
        pointerOpenProjectPanel = new javax.swing.JPanel();
        openProjectLabel = new javax.swing.JLabel();
        openProjectIconLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        calculatorContentPanel = new javax.swing.JPanel();
        exitLabel1 = new javax.swing.JLabel();
        easyMCULabel1 = new javax.swing.JLabel();
        learnContentPanel1 = new javax.swing.JPanel();
        exitLabel2 = new javax.swing.JLabel();
        easyMCULabel2 = new javax.swing.JLabel();
        aboutContentPanel = new javax.swing.JPanel();
        exitLabel3 = new javax.swing.JLabel();
        easyMCULabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Easy MCU");
        setBackground(new java.awt.Color(35, 64, 102));
        setLocationByPlatform(true);
        setName("EasyMCUFrame"); // NOI18N
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        sidePanel.setBackground(new java.awt.Color(35, 64, 102));
        sidePanel.setForeground(new java.awt.Color(35, 64, 102));

        newProjectPanel.setBackground(new java.awt.Color(35, 64, 102));
        newProjectPanel.setForeground(new java.awt.Color(35, 64, 102));
        newProjectPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                newProjectPanelMouseMoved(evt);
            }
        });
        newProjectPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newProjectPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newProjectPanelMouseExited(evt);
            }
        });

        pointerNewProjectPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerNewProjectPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerNewProjectPanel.setOpaque(false);

        javax.swing.GroupLayout pointerNewProjectPanelLayout = new javax.swing.GroupLayout(pointerNewProjectPanel);
        pointerNewProjectPanel.setLayout(pointerNewProjectPanelLayout);
        pointerNewProjectPanelLayout.setHorizontalGroup(
            pointerNewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerNewProjectPanelLayout.setVerticalGroup(
            pointerNewProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        newProjectLabel.setBackground(new java.awt.Color(35, 64, 102));
        newProjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        newProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newProjectLabel.setText("New Project");
        newProjectLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newProjectIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout newProjectPanelLayout = new javax.swing.GroupLayout(newProjectPanel);
        newProjectPanel.setLayout(newProjectPanelLayout);
        newProjectPanelLayout.setHorizontalGroup(
            newProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newProjectPanelLayout.createSequentialGroup()
                .addComponent(pointerNewProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(newProjectIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        newProjectPanelLayout.setVerticalGroup(
            newProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerNewProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(newProjectPanelLayout.createSequentialGroup()
                .addComponent(newProjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(newProjectIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CalculatorPanel.setBackground(new java.awt.Color(35, 64, 102));
        CalculatorPanel.setForeground(new java.awt.Color(35, 64, 102));
        CalculatorPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CalculatorPanelMouseMoved(evt);
            }
        });
        CalculatorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatorPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalculatorPanelMouseExited(evt);
            }
        });

        pointerCalculatorPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerCalculatorPanel.setOpaque(false);

        javax.swing.GroupLayout pointerCalculatorPanelLayout = new javax.swing.GroupLayout(pointerCalculatorPanel);
        pointerCalculatorPanel.setLayout(pointerCalculatorPanelLayout);
        pointerCalculatorPanelLayout.setHorizontalGroup(
            pointerCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerCalculatorPanelLayout.setVerticalGroup(
            pointerCalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        calculatorLabel.setBackground(new java.awt.Color(35, 64, 102));
        calculatorLabel.setForeground(new java.awt.Color(255, 255, 255));
        calculatorLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calculatorLabel.setText("MCU Calculator");

        calculatorIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout CalculatorPanelLayout = new javax.swing.GroupLayout(CalculatorPanel);
        CalculatorPanel.setLayout(CalculatorPanelLayout);
        CalculatorPanelLayout.setHorizontalGroup(
            CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPanelLayout.createSequentialGroup()
                .addComponent(pointerCalculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(calculatorIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CalculatorPanelLayout.setVerticalGroup(
            CalculatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calculatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(calculatorIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LearnPanel.setBackground(new java.awt.Color(35, 64, 102));
        LearnPanel.setForeground(new java.awt.Color(35, 64, 102));
        LearnPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LearnPanelMouseMoved(evt);
            }
        });
        LearnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LearnPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LearnPanelMouseExited(evt);
            }
        });

        pointerLearnPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerLearnPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerLearnPanel.setOpaque(false);

        javax.swing.GroupLayout pointerLearnPanelLayout = new javax.swing.GroupLayout(pointerLearnPanel);
        pointerLearnPanel.setLayout(pointerLearnPanelLayout);
        pointerLearnPanelLayout.setHorizontalGroup(
            pointerLearnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerLearnPanelLayout.setVerticalGroup(
            pointerLearnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        learnLabel.setBackground(new java.awt.Color(35, 64, 102));
        learnLabel.setForeground(new java.awt.Color(255, 255, 255));
        learnLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        learnLabel.setText("Learn & Discover");

        learnIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout LearnPanelLayout = new javax.swing.GroupLayout(LearnPanel);
        LearnPanel.setLayout(LearnPanelLayout);
        LearnPanelLayout.setHorizontalGroup(
            LearnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnPanelLayout.createSequentialGroup()
                .addComponent(pointerLearnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(learnIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(learnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        LearnPanelLayout.setVerticalGroup(
            LearnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerLearnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(learnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(learnIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logoPanel.setBackground(new java.awt.Color(35, 64, 102));
        logoPanel.setForeground(new java.awt.Color(35, 64, 102));
        logoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoPanelMouseClicked(evt);
            }
        });

        logoLabel.setBackground(new java.awt.Color(35, 64, 102));
        logoLabel.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        AboutPanel.setBackground(new java.awt.Color(35, 64, 102));
        AboutPanel.setForeground(new java.awt.Color(35, 64, 102));
        AboutPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AboutPanelMouseMoved(evt);
            }
        });
        AboutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutPanelMouseExited(evt);
            }
        });

        pointerAboutPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerAboutPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerAboutPanel.setOpaque(false);

        javax.swing.GroupLayout pointerAboutPanelLayout = new javax.swing.GroupLayout(pointerAboutPanel);
        pointerAboutPanel.setLayout(pointerAboutPanelLayout);
        pointerAboutPanelLayout.setHorizontalGroup(
            pointerAboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerAboutPanelLayout.setVerticalGroup(
            pointerAboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        aboutLabel.setBackground(new java.awt.Color(35, 64, 102));
        aboutLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aboutLabel.setText("About & Feedback");

        aboutIconLabel.setBackground(new java.awt.Color(35, 64, 102));

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(pointerAboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(aboutIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerAboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(aboutIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LearnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CalculatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LearnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generalPanel.setLayout(new java.awt.CardLayout());

        recentProjectsPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setText("X");
        exitLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabelMouseMoved(evt);
            }
        });
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        easyMCULabel.setBackground(new java.awt.Color(82, 133, 212));
        easyMCULabel.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        easyMCULabel.setForeground(new java.awt.Color(255, 255, 255));
        easyMCULabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyMCULabel.setLabelFor(logoLabel);
        easyMCULabel.setText("EasyMCU");

        recentProjectsLabel.setBackground(new java.awt.Color(82, 133, 212));
        recentProjectsLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        recentProjectsLabel.setForeground(new java.awt.Color(255, 255, 255));
        recentProjectsLabel.setText("Recent Projects");

        jScrollPane1.setBackground(new java.awt.Color(82, 133, 212));

        jTable1.setBackground(new java.awt.Color(254, 254, 254));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project Name", "Project Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(71, 120, 197));
        jScrollPane1.setViewportView(jTable1);

        openProjectPanel.setBackground(new java.awt.Color(35, 64, 102));
        openProjectPanel.setForeground(new java.awt.Color(35, 64, 102));
        openProjectPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                openProjectPanelMouseMoved(evt);
            }
        });
        openProjectPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openProjectPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openProjectPanelMouseExited(evt);
            }
        });

        pointerOpenProjectPanel.setBackground(new java.awt.Color(255, 128, 0));
        pointerOpenProjectPanel.setForeground(new java.awt.Color(35, 64, 102));
        pointerOpenProjectPanel.setOpaque(false);

        javax.swing.GroupLayout pointerOpenProjectPanelLayout = new javax.swing.GroupLayout(pointerOpenProjectPanel);
        pointerOpenProjectPanel.setLayout(pointerOpenProjectPanelLayout);
        pointerOpenProjectPanelLayout.setHorizontalGroup(
            pointerOpenProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pointerOpenProjectPanelLayout.setVerticalGroup(
            pointerOpenProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        openProjectLabel.setBackground(new java.awt.Color(35, 64, 102));
        openProjectLabel.setForeground(new java.awt.Color(255, 255, 255));
        openProjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        openProjectLabel.setText("Open Project");

        javax.swing.GroupLayout openProjectPanelLayout = new javax.swing.GroupLayout(openProjectPanel);
        openProjectPanel.setLayout(openProjectPanelLayout);
        openProjectPanelLayout.setHorizontalGroup(
            openProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openProjectPanelLayout.createSequentialGroup()
                .addComponent(pointerOpenProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openProjectIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );
        openProjectPanelLayout.setVerticalGroup(
            openProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointerOpenProjectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(openProjectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
            .addComponent(openProjectIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        errorLabel.setForeground(new java.awt.Color(255, 0, 13));

        javax.swing.GroupLayout recentProjectsPanelLayout = new javax.swing.GroupLayout(recentProjectsPanel);
        recentProjectsPanel.setLayout(recentProjectsPanelLayout);
        recentProjectsPanelLayout.setHorizontalGroup(
            recentProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recentProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recentProjectsPanelLayout.createSequentialGroup()
                        .addGap(185, 483, Short.MAX_VALUE)
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recentProjectsPanelLayout.createSequentialGroup()
                        .addGroup(recentProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                            .addComponent(easyMCULabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recentProjectsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(recentProjectsPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(errorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        recentProjectsPanelLayout.setVerticalGroup(
            recentProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recentProjectsPanelLayout.createSequentialGroup()
                .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(easyMCULabel)
                .addGap(24, 24, 24)
                .addComponent(recentProjectsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(recentProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openProjectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recentProjectsPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(errorLabel)))
                .addContainerGap())
        );

        generalPanel.add(recentProjectsPanel, "card2");

        calculatorContentPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel1.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel1.setText("X");
        exitLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabel1MouseMoved(evt);
            }
        });
        exitLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel1MouseExited(evt);
            }
        });

        easyMCULabel1.setBackground(new java.awt.Color(82, 133, 212));
        easyMCULabel1.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        easyMCULabel1.setForeground(new java.awt.Color(255, 255, 255));
        easyMCULabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyMCULabel1.setLabelFor(logoLabel);
        easyMCULabel1.setText("EasyMCU Calculator");

        javax.swing.GroupLayout calculatorContentPanelLayout = new javax.swing.GroupLayout(calculatorContentPanel);
        calculatorContentPanel.setLayout(calculatorContentPanelLayout);
        calculatorContentPanelLayout.setHorizontalGroup(
            calculatorContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculatorContentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calculatorContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(easyMCULabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        calculatorContentPanelLayout.setVerticalGroup(
            calculatorContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculatorContentPanelLayout.createSequentialGroup()
                .addComponent(exitLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(easyMCULabel1)
                .addGap(0, 448, Short.MAX_VALUE))
        );

        generalPanel.add(calculatorContentPanel, "card3");

        learnContentPanel1.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel2.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel2.setText("X");
        exitLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabel2MouseMoved(evt);
            }
        });
        exitLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel2MouseExited(evt);
            }
        });

        easyMCULabel2.setBackground(new java.awt.Color(82, 133, 212));
        easyMCULabel2.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        easyMCULabel2.setForeground(new java.awt.Color(255, 255, 255));
        easyMCULabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyMCULabel2.setLabelFor(logoLabel);
        easyMCULabel2.setText("Learn EasyMCU");

        javax.swing.GroupLayout learnContentPanel1Layout = new javax.swing.GroupLayout(learnContentPanel1);
        learnContentPanel1.setLayout(learnContentPanel1Layout);
        learnContentPanel1Layout.setHorizontalGroup(
            learnContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learnContentPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learnContentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(easyMCULabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        learnContentPanel1Layout.setVerticalGroup(
            learnContentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(learnContentPanel1Layout.createSequentialGroup()
                .addComponent(exitLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(easyMCULabel2)
                .addGap(0, 448, Short.MAX_VALUE))
        );

        generalPanel.add(learnContentPanel1, "card3");

        aboutContentPanel.setBackground(new java.awt.Color(82, 133, 212));

        exitLabel3.setBackground(new java.awt.Color(82, 133, 212));
        exitLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        exitLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel3.setText("X");
        exitLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                exitLabel3MouseMoved(evt);
            }
        });
        exitLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabel3MouseExited(evt);
            }
        });

        easyMCULabel3.setBackground(new java.awt.Color(82, 133, 212));
        easyMCULabel3.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        easyMCULabel3.setForeground(new java.awt.Color(255, 255, 255));
        easyMCULabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyMCULabel3.setLabelFor(logoLabel);
        easyMCULabel3.setText("About EasyMCU");

        javax.swing.GroupLayout aboutContentPanelLayout = new javax.swing.GroupLayout(aboutContentPanel);
        aboutContentPanel.setLayout(aboutContentPanelLayout);
        aboutContentPanelLayout.setHorizontalGroup(
            aboutContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutContentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(easyMCULabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        aboutContentPanelLayout.setVerticalGroup(
            aboutContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutContentPanelLayout.createSequentialGroup()
                .addComponent(exitLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(easyMCULabel3)
                .addGap(0, 448, Short.MAX_VALUE))
        );

        generalPanel.add(aboutContentPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseExited
        exitLabel.setForeground(Color.black);
    }//GEN-LAST:event_exitLabelMouseExited

    private void exitLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseMoved
        exitLabel.setForeground(Color.red);
    }//GEN-LAST:event_exitLabelMouseMoved

    private void newProjectPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProjectPanelMouseMoved
        
        DV.movingMouseStyle(newProjectPanel, pointerNewProjectPanel, newProjectLabel, panelMovingColor, labelMovingColor);

    }//GEN-LAST:event_newProjectPanelMouseMoved

    private void newProjectPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProjectPanelMouseExited
        DV.exiteMouseStyle(newProjectPanel, pointerNewProjectPanel, newProjectLabel);
    }//GEN-LAST:event_newProjectPanelMouseExited

    private void CalculatorPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorPanelMouseMoved
       
        DV.movingMouseStyle(CalculatorPanel, pointerCalculatorPanel, calculatorLabel, panelMovingColor, labelMovingColor);

    }//GEN-LAST:event_CalculatorPanelMouseMoved

    private void CalculatorPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorPanelMouseExited
        DV.exiteMouseStyle(CalculatorPanel, pointerCalculatorPanel, calculatorLabel);

    }//GEN-LAST:event_CalculatorPanelMouseExited

    private void LearnPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnPanelMouseMoved
        DV.movingMouseStyle(LearnPanel, pointerLearnPanel, learnLabel, panelMovingColor, labelMovingColor);

    }//GEN-LAST:event_LearnPanelMouseMoved

    private void openProjectPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectPanelMouseMoved
        DV.movingMouseStyle(openProjectPanel, pointerOpenProjectPanel, openProjectLabel, panelMovingColor, labelMovingColor);

    }//GEN-LAST:event_openProjectPanelMouseMoved

    private void openProjectPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectPanelMouseExited
        DV.exiteMouseStyle(openProjectPanel, pointerOpenProjectPanel, openProjectLabel);
    }//GEN-LAST:event_openProjectPanelMouseExited

    private void LearnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnPanelMouseExited
        DV.exiteMouseStyle(LearnPanel, pointerLearnPanel, learnLabel);
    }//GEN-LAST:event_LearnPanelMouseExited

    private void AboutPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutPanelMouseMoved
        DV.movingMouseStyle(AboutPanel, pointerAboutPanel, aboutLabel, panelMovingColor, labelMovingColor);

    }//GEN-LAST:event_AboutPanelMouseMoved

    private void AboutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutPanelMouseExited
        DV.exiteMouseStyle(AboutPanel, pointerAboutPanel, aboutLabel);

    }//GEN-LAST:event_AboutPanelMouseExited

    private void openProjectPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openProjectPanelMouseClicked
        try {
            String Location=(String) jTable1.getValueAt(jTable1.getSelectedRow(), 1), Name=(String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            errorLabel.setText("");
            CurrentProject project = new CurrentProject(Location,Name);
            project.setVisible(true);
        } catch (Exception e) {
            errorLabel.setText("Please choose a Project");
        }
    }//GEN-LAST:event_openProjectPanelMouseClicked

    private void newProjectPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProjectPanelMouseClicked
        NewProject newProject = new NewProject();
        newProject.setVisible(true);
    }//GEN-LAST:event_newProjectPanelMouseClicked

    private void exitLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseMoved
        exitLabel1.setForeground(Color.red);    }//GEN-LAST:event_exitLabel1MouseMoved

    private void exitLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel1MouseClicked

    private void exitLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel1MouseExited
        exitLabel1.setForeground(Color.black);
    }//GEN-LAST:event_exitLabel1MouseExited

    private void CalculatorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatorPanelMouseClicked
        DV.switchPanelTo(generalPanel, calculatorContentPanel);
    }//GEN-LAST:event_CalculatorPanelMouseClicked

    private void logoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoPanelMouseClicked
        DV.switchPanelTo(generalPanel, recentProjectsPanel);

    }//GEN-LAST:event_logoPanelMouseClicked

    private void exitLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseMoved
        exitLabel2.setForeground(Color.red);
    }//GEN-LAST:event_exitLabel2MouseMoved

    private void exitLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel2MouseClicked

    private void exitLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel2MouseExited
        exitLabel2.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabel2MouseExited

    private void LearnPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LearnPanelMouseClicked
        DV.switchPanelTo(generalPanel, learnContentPanel1);
    }//GEN-LAST:event_LearnPanelMouseClicked

    private void exitLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseMoved
        exitLabel3.setForeground(Color.red);
    }//GEN-LAST:event_exitLabel3MouseMoved

    private void exitLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabel3MouseClicked

    private void exitLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabel3MouseExited
       exitLabel3.setForeground(Color.BLACK);
    }//GEN-LAST:event_exitLabel3MouseExited

    private void AboutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutPanelMouseClicked
        DV.switchPanelTo(generalPanel, aboutContentPanel);
    }//GEN-LAST:event_AboutPanelMouseClicked
    int xx, xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    public void updateTable() {
        aFile.insertDataToTable(jTable1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyMCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyMCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyMCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyMCU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyMCU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel CalculatorPanel;
    private javax.swing.JPanel LearnPanel;
    private javax.swing.JPanel aboutContentPanel;
    private javax.swing.JLabel aboutIconLabel;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel calculatorContentPanel;
    private javax.swing.JLabel calculatorIconLabel;
    private javax.swing.JLabel calculatorLabel;
    private javax.swing.JLabel easyMCULabel;
    private javax.swing.JLabel easyMCULabel1;
    private javax.swing.JLabel easyMCULabel2;
    private javax.swing.JLabel easyMCULabel3;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel exitLabel1;
    private javax.swing.JLabel exitLabel2;
    private javax.swing.JLabel exitLabel3;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel learnContentPanel1;
    private javax.swing.JLabel learnIconLabel;
    private javax.swing.JLabel learnLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel newProjectIconLabel;
    private javax.swing.JLabel newProjectLabel;
    private javax.swing.JPanel newProjectPanel;
    private javax.swing.JLabel openProjectIconLabel;
    private javax.swing.JLabel openProjectLabel;
    private javax.swing.JPanel openProjectPanel;
    private javax.swing.JPanel pointerAboutPanel;
    private javax.swing.JPanel pointerCalculatorPanel;
    private javax.swing.JPanel pointerLearnPanel;
    private javax.swing.JPanel pointerNewProjectPanel;
    private javax.swing.JPanel pointerOpenProjectPanel;
    private javax.swing.JLabel recentProjectsLabel;
    private javax.swing.JPanel recentProjectsPanel;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
