#ifndef _USART_CONFIG_H
#define _USART_CONFIG_H

#define MODE_OF_OPERATION				SYNCHRONOUS
#define SPEED_OPERATION				DOUBLE_SPEED_MODE
#define PARITY_MODE				DISABLED
#define STOP_BIT_SELECT				TWO_BIT
#define CLOCK_POLARITY				FALLING
#define F_CPU				16000000L
#define FRAME_SIZE				8
#define BAUD_RATE				9600L

#endif
