#ifndef _ADC_CONFIG_H
#define _ADC_CONFIG_H

#define VOLTAGE_REFERENCE				AREF
#define ADJUSTMENT				RIGHT_ADJUSTMENT
#define ADC_AUTO_TRIGGER_SOURCE				ANALOG_COMPARATOR
#define ADC_PRESCALLER				DIVID_BY_16

#endif
